name: cooler_themes
description: A collection of beautiful themes for your next Flutter app. Ideal for fast prototyping.
version: 0.1.0
author: Vince Varga <vince.varga@serial.dev>
homepage: https://github.com/dartsidedev/cooler_themes
issue_tracker: https://github.com/dartsidedev/cooler_themes/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
